### ISSUE TITLE
Capitalization in policy conditions breaks the conditions

### ISSUE THREAD

**Issue by ankon** [Collaborne/kubernetes-aws-resource-service#16]
We capitalize the field names so that the resources look more kubernetes-y. This breaks for policies with conditions such as this one:
```yaml
condition:
 stringEquals:
  'ses:FromAddress': "some@example.com"
```

The `ses:FromAddress` is a special value (see http://docs.aws.amazon.com/ses/latest/DeveloperGuide/control-user-access.html), and must not be capitalized. The same can happen for other condition entries.
